### ISSUE TITLE
setting alpha and beta

### ISSUE THREAD

**Issue by armintabari** [mfaruqui/retrofitting#4]
For the experiments in the paper you noted that you set alpha as 1, and beta as degree(i)^-1. 
I am trying to change and use the code here (as I understand both alpha and beta are assumed to be 1 here), but what exactly do you mean by  degree(i)^-1?
Is it the angle between the word being updated and the current neighbor? 
I'd appreciate it if you could clear this up for me.

**Comment by armintabari** [comment]
Could you please clarify this?
Thank you.

**Comment by nooralahzadeh** [comment]
for each neighbour of i , beta is equal to degree(i)^-1 means that  beta=1/number of neighbours
degree(i) =number of neighbours
since alpha=1, when you put in formula it becomes: new_vector_for_word= [(1/number of neighbours)*(SUM_all_neighbours_vector) + pre_vector_for_word ] / 2
or [SUM_all_neighbours_vector + number of neighbours*pre_vector_for_word]/(2*number of neighbours)

**Comment by armintabari** [comment]
Thank you.
